Gemspec/RequiredRubyVersion:
  Enabled: No

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  ExcludedMethods: describe

Metrics/AbcSize:
  Enabled: No

Style/Documentation:
  Enabled: No

Style/DoubleNegation:
  Enabled: No

Naming/FileName:
  Enabled: No
